version: '3.8'

services:
  neoserve-ai:
    build: .
    container_name: neoserve-ai
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    depends_on:
      - redis
      - firestore-emulator
    restart: unless-stopped
    networks:
      - neoserve-network
    command: >
      sh -c "uvicorn neoserve_ai.main:app --host 0.0.0.0 --port 8000 --reload"

  redis:
    image: redis:7-alpine
    container_name: neoserve-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - neoserve-network
    restart: unless-stopped

  firestore-emulator:
    image: mtlynch/firestore-emulator
    container_name: firestore-emulator
    ports:
      - "8080:8080"
    environment:
      - FIRESTORE_PROJECT_ID=neoserve-ai
      - FIRESTORE_PORT=8080
    networks:
      - neoserve-network
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - neoserve-network

networks:
  neoserve-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
