services:
  - type: web
    name: neoserve-ai
    env: docker
    dockerfile: Dockerfile.prod
    dockerContext: .
    dockerCommand: /app/start_services.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
      - key: API_URL
        value: /api
      - key: ENVIRONMENT
        value: production
      - key: NODE_ENV
        value: production
    buildCommand: |
      docker build -f Dockerfile.prod -t neoserve-ai .
    startCommand: docker run -p 10000:80 neoserve-ai
