services:
  - type: web
    name: neoserve-ai
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn neoserve_ai.main:app --worker-class uvicorn.workers.UvicornWorker --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000
